### ISSUE TITLE
Error playing Vimeo videos

### ISSUE THREAD

**Issue by yargeel** [vimeo/PlayerKit#54]
Hello!
I'm developing an app with Vimeo Pro videos. 
Backend gives urls like this: "https://vimeo.com/283472685/e184291bed", but PlayerKit reports error "PlayerKit_Example[1709:19210] 🚫 Optional(Error Domain=NSOSStatusErrorDomain Code=-12660 "(null)")".
Is there "getting started" for newbies (looking for it on developer.vimeo.com, but have no success)?
Thank you in advance!

**Comment by suneelseelam** [comment]
Hi Team,

               We are trying to play Vimeo videos demo url like : "https://player.vimeo.com/video/9011932" with the help of playerkit , we are not able to play , and I tried this "https://github.com/vimeo/PlayerKit/blob/master/Example/PlayerKit/video.mp4?raw=true"  it has been played . we has to add any extension to the video url?, I haven't get any "playerstatus" too. Please help us out.

Thanks In advance!

**Comment by nicolelehrer** [comment]
Hi @yargeel, the URL you provided is for videos with a special privacy (they're only visible to those who have the link). You shouldn't have trouble fetching the playable files for these links but the request requires some special formatting in order to get the playable files. First off
- What kind of Vimeo account do you have (e.g. basic, pro, plus)? This would be the account that you used to create your app on the API site https://developer.vimeo.com/api/guides/start#generate-access-token
- Are you trying to play your videos or those of another Vimeo user?
- Note that setting the URL `https://vimeo.com/283472685/e184291bed` as the AVAssetURL will not play the video in PlayerKit. You must interact with the Vimeo API in order to get the video files from our CDN. We can point you in the right direction if needed on how to do that.

**Comment by nicolelehrer** [comment]
@suneelseelam the last point in my previous comment might answer your question as well - that video is playing because the URL `https://github.com/vimeo/PlayerKit/blob/master/Example/PlayerKit/video.mp4?raw=true` points to the file itself.  In order to get the equivalent files for Vimeo videos, you'll need to interact with the Vimeo API. When you can, let us know your account type and the video files you'd like to access (for more info, check out the first 2 bullets listed above). Thanks!

**Comment by ergunkocak** [comment]
@suneelseelam 

For non private videos do we still to use api? For example can i use this url: https://player.vimeo.com/video/304846250

Best

**Comment by nicolelehrer** [comment]
@ergunkocak That's right, you'd still need to use the Vimeo API to get a playback URL for PlayerKit.

**Comment by Cristy4** [comment]
Hi,I think I have the same problem, can you post an example for set Vimeo API to get an url with access token?
